### Health check
GET http://localhost:3000/health

### DB Health check
GET http://localhost:3000/health/db

### Select users
GET http://localhost:3000/usuarios

### Create user
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "userTeste",
  "email": "user@teste.com",
  "senha": "userTeste"
}

### Listar grupos
GET http://localhost:3000/grupos

### Criar grupo
POST http://localhost:3000/grupos
Content-Type: application/json

{
  "nome": "Pelada de Sábado",
  "descricao": "Pelada da firma, todo Sábado às 14h",
  "dia_semana": 6,
  "horario": "14:00",
  "local": "Campo da Santa Fé",
  "usuario_id": 29
}